//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lipository.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 340")]
        public global::System.Drawing.Size TotalInfoSize {
            get {
                return ((global::System.Drawing.Size)(this["TotalInfoSize"]));
            }
            set {
                this["TotalInfoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 165")]
        public global::System.Drawing.Size ImageInfoSize {
            get {
                return ((global::System.Drawing.Size)(this["ImageInfoSize"]));
            }
            set {
                this["ImageInfoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9, 9")]
        public global::System.Drawing.Point ImageInfoPos {
            get {
                return ((global::System.Drawing.Point)(this["ImageInfoPos"]));
            }
            set {
                this["ImageInfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImageInfoVisible {
            get {
                return ((bool)(this["ImageInfoVisible"]));
            }
            set {
                this["ImageInfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TitleInfoText {
            get {
                return ((string)(this["TitleInfoText"]));
            }
            set {
                this["TitleInfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 175")]
        public global::System.Drawing.Point TitleInfoPos {
            get {
                return ((global::System.Drawing.Point)(this["TitleInfoPos"]));
            }
            set {
                this["TitleInfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TitleInfoVisible {
            get {
                return ((bool)(this["TitleInfoVisible"]));
            }
            set {
                this["TitleInfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubTitleInfoText {
            get {
                return ((string)(this["SubTitleInfoText"]));
            }
            set {
                this["SubTitleInfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 200")]
        public global::System.Drawing.Point SubTitleInfoPos {
            get {
                return ((global::System.Drawing.Point)(this["SubTitleInfoPos"]));
            }
            set {
                this["SubTitleInfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SubTitleVisible {
            get {
                return ((bool)(this["SubTitleVisible"]));
            }
            set {
                this["SubTitleVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RateInfoText {
            get {
                return ((string)(this["RateInfoText"]));
            }
            set {
                this["RateInfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125, 200")]
        public global::System.Drawing.Point RateInfoPos {
            get {
                return ((global::System.Drawing.Point)(this["RateInfoPos"]));
            }
            set {
                this["RateInfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RateInfoVisible {
            get {
                return ((bool)(this["RateInfoVisible"]));
            }
            set {
                this["RateInfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Etc1InfoTitle {
            get {
                return ((string)(this["Etc1InfoTitle"]));
            }
            set {
                this["Etc1InfoTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Etc1InfoText {
            get {
                return ((string)(this["Etc1InfoText"]));
            }
            set {
                this["Etc1InfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 215")]
        public global::System.Drawing.Point Etc1InfoPos {
            get {
                return ((global::System.Drawing.Point)(this["Etc1InfoPos"]));
            }
            set {
                this["Etc1InfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Etc1InfoVisible {
            get {
                return ((bool)(this["Etc1InfoVisible"]));
            }
            set {
                this["Etc1InfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Etc2InfoTitle {
            get {
                return ((string)(this["Etc2InfoTitle"]));
            }
            set {
                this["Etc2InfoTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Etc2InfoText {
            get {
                return ((string)(this["Etc2InfoText"]));
            }
            set {
                this["Etc2InfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 230")]
        public global::System.Drawing.Point Etc2InfoPos {
            get {
                return ((global::System.Drawing.Point)(this["Etc2InfoPos"]));
            }
            set {
                this["Etc2InfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Etc2InfoVisible {
            get {
                return ((bool)(this["Etc2InfoVisible"]));
            }
            set {
                this["Etc2InfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Etc3InfoTitle {
            get {
                return ((string)(this["Etc3InfoTitle"]));
            }
            set {
                this["Etc3InfoTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Etc3InfoText {
            get {
                return ((string)(this["Etc3InfoText"]));
            }
            set {
                this["Etc3InfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 245")]
        public global::System.Drawing.Point Etc3InfoPos {
            get {
                return ((global::System.Drawing.Point)(this["Etc3InfoPos"]));
            }
            set {
                this["Etc3InfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Etc3InfoVisible {
            get {
                return ((bool)(this["Etc3InfoVisible"]));
            }
            set {
                this["Etc3InfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Etc4InfoTitle {
            get {
                return ((string)(this["Etc4InfoTitle"]));
            }
            set {
                this["Etc4InfoTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Etc4InfoText {
            get {
                return ((string)(this["Etc4InfoText"]));
            }
            set {
                this["Etc4InfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 260")]
        public global::System.Drawing.Point Etc4InfoPos {
            get {
                return ((global::System.Drawing.Point)(this["Etc4InfoPos"]));
            }
            set {
                this["Etc4InfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Etc4InfoVisible {
            get {
                return ((bool)(this["Etc4InfoVisible"]));
            }
            set {
                this["Etc4InfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemoInfoText {
            get {
                return ((string)(this["MemoInfoText"]));
            }
            set {
                this["MemoInfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 275")]
        public global::System.Drawing.Point MemoInfoPos {
            get {
                return ((global::System.Drawing.Point)(this["MemoInfoPos"]));
            }
            set {
                this["MemoInfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemoInfoVisible {
            get {
                return ((bool)(this["MemoInfoVisible"]));
            }
            set {
                this["MemoInfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseInfoText {
            get {
                return ((string)(this["ReleaseInfoText"]));
            }
            set {
                this["ReleaseInfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 290")]
        public global::System.Drawing.Point ReleaseInfoPos {
            get {
                return ((global::System.Drawing.Point)(this["ReleaseInfoPos"]));
            }
            set {
                this["ReleaseInfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReleaseInfoVisible {
            get {
                return ((bool)(this["ReleaseInfoVisible"]));
            }
            set {
                this["ReleaseInfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastInfoText {
            get {
                return ((string)(this["LastInfoText"]));
            }
            set {
                this["LastInfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 305")]
        public global::System.Drawing.Point LastInfoPos {
            get {
                return ((global::System.Drawing.Point)(this["LastInfoPos"]));
            }
            set {
                this["LastInfoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LastInfoVisible {
            get {
                return ((bool)(this["LastInfoVisible"]));
            }
            set {
                this["LastInfoVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avi,mp4,wmv,mpg,mkv,mov,ts,tp,flv")]
        public string MediaExtensions {
            get {
                return ((string)(this["MediaExtensions"]));
            }
            set {
                this["MediaExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpg,jpeg,png,bmp")]
        public string ImageExtensions {
            get {
                return ((string)(this["ImageExtensions"]));
            }
            set {
                this["ImageExtensions"] = value;
            }
        }
    }
}
